{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#default_exp explorer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "from fastai2.vision.all import *\n",
    "from fastexplorer.representation import *\n",
    "from starlette.applications import Starlette\n",
    "from starlette.endpoints import WebSocketEndpoint\n",
    "from starlette.websockets import WebSocketDisconnect\n",
    "import uvicorn, asyncio, json, logging\n",
    "import nest_asyncio\n",
    "nest_asyncio.apply()\n",
    "logger = logging.getLogger()\n",
    "logger.setLevel(logging.INFO)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#hide\n",
    "%reload_ext autoreload\n",
    "%autoreload 2\n",
    "from nbdev.showdoc import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "path = untar_data(URLs.MNIST_TINY)\n",
    "dls = ImageDataLoaders.from_folder(path)\n",
    "learn = cnn_learner(dls, resnet18, pretrained=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Fast Explorer\n",
    "\n",
    "> Here we will setup the server and store the model representation on the fastai `Learn` object.."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "class FastExplorer:\n",
    "    'Wrapper around `Representation` and `ProxyServer`.'\n",
    "    def __init__(self, learn, host='0.0.0.0', port=8000):\n",
    "        store_attr(self, 'learn,host,port')\n",
    "        self.representation = learn.to_representation()\n",
    "        self.server = Starlette()\n",
    "        self.endpoint = self.server.websocket_route('/ws')(self.endpoint)\n",
    "        self.socket = None\n",
    "        \n",
    "    def __repr__(self): return f'{self.__class__.__name__} ()'\n",
    "\n",
    "    async def handle_web_client(self, websocket):\n",
    "        while True:\n",
    "            try:\n",
    "                msg = await websocket.receive_json()\n",
    "                logging.info(f'Client msg: {msg}')\n",
    "                await self.dispatch_event(websocket, msg)\n",
    "            except json.JSONDecodeError: logging.info('Invalid JSON received')\n",
    "            except WebSocketDisconnect: break\n",
    "    \n",
    "    async def dispatch_event(self, websocket, msg):\n",
    "        event = msg['event']\n",
    "        if not hasattr(self, 'event'):\n",
    "            logging.info(f'Invalid event: {event}')\n",
    "            await websocket.send_json({'event': 'invalid_event', 'msg': event})\n",
    "    \n",
    "    async def endpoint(self, websocket):\n",
    "        # Open socket\n",
    "        await websocket.accept()\n",
    "        msg = await websocket.receive_json()\n",
    "        self.socket = websocket\n",
    "        logging.info(f'Client connected: {msg}')\n",
    "        \n",
    "        # Manage requests\n",
    "        await websocket.send_json({'event': 'representation_data', 'msg': self.representation.to_json()})\n",
    "        await self.handle_web_client(websocket)\n",
    "        \n",
    "        # Close socket\n",
    "        await close_client(websocket, 'Finalized by server')\n",
    "        logging.info(f'Client closed: {msg}')    \n",
    "    \n",
    "    def serve(self): uvicorn.run(self.server, host=self.host, port=self.port)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "async def close_client(websocket, msg):\n",
    "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
    "    await websocket.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "@patch\n",
    "@delegates(FastExplorer.__init__)\n",
    "def fastexplorer(self:Learner, reload=False, **kwargs):\n",
    "    if (not hasattr(self, 'explorer')) or reload: self.explorer = FastExplorer(self, **kwargs)\n",
    "    self.explorer.serve()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Started server process [4440]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)\n",
      "INFO:     ('127.0.0.1', 48402) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 48622) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 48772) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     ('127.0.0.1', 54640) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 54804) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 55272) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 35502) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     ('127.0.0.1', 35654) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 37274) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 37308) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 38030) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     ('127.0.0.1', 38608) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 38698) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 39112) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 39236) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     ('127.0.0.1', 39260) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 39280) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 39296) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-31-ecc546f94c4a>\", line 40, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-32-1c1d1aec635e>\", line 3, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     Shutting down\n",
      "INFO:     Waiting for application shutdown.\n",
      "INFO:     Application shutdown complete.\n",
      "INFO:     Finished server process [4440]\n"
     ]
    }
   ],
   "source": [
    "#hide\n",
    "learn.fastexplorer(True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Export -"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Converted 00_representation.ipynb.\n",
      "Converted 01_explorer.ipynb.\n",
      "Converted 10_tutorial.ipynb.\n",
      "Converted index.ipynb.\n"
     ]
    }
   ],
   "source": [
    "#hide\n",
    "from nbdev.export import notebook2script\n",
    "notebook2script()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ml2",
   "language": "python",
   "name": "ml2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
